library(dplyr)

#####################################################################
# Make example demand data by customer, product, and destination
#
# The data is generated by finding all the possible combinations of
# the three hierarchy levels and then, for each combination,
# generating a time series which is in the form of:
# demand = const + seasonal_variation + gaussian_noise
#
# The main function is exampleDataGen. It will return a data frame
# with our defined historic demand schema. See function def for
# input list
#
#####################################################################

# Default Hierarchy 
customerList <- c("Contoso","Protoso")
productCategories <- c("Plastics","Metals")
destinationList <- c("China","United States","India")

# Do some hacky outer products to generate the full data frame of product hierarchies
getCombos <- function(customerList, productCategories, destinationList) {
  
  ncust <- length(customerList)
  nprod <- length(productCategories)
  ndest <- length(destinationList)
  
  midlayer <- lapply(1:(ncust*nprod), 
                 function(i) c(customerList[floor((i-1)/nprod) + 1], productCategories[(i-1)%%nprod + 1]))
  
  lowlayer <- lapply(1:(ncust*nprod*ndest),
                 function(i) c(midlayer[[floor((i-1)/ndest) + 1]], destinationList[(i-1)%%ndest + 1]))
  
  combo.df <- bind_rows(lapply(lowlayer, 
                               function(v) as.data.frame(matrix(v, nrow = 1))))
  colnames(combo.df) <- c("CustomerName","ProductCategory","Destination")
  
  return(combo.df)
}

generateDemand <- function(startDate = as.Date("2015-01-01"),
                           endDate = as.Date("2017-05-01"),
                           baselineDemand = 100,
                           seasonalAmp=10, seasonalPhase=0, noiseSigma=5) {
  
  months <- seq(from=startDate, to=endDate, by="month")
  monthsElapsed <- seq(from=0, along.with = months)
  nmonths <- length(months)
  
  # make some very fake demand data
  demand <- baselineDemand + seasonalAmp*cos(2*pi*(monthsElapsed - seasonalPhase)/12) + 
    rnorm(nmonths, sd = noiseSigma) 
  demand <- round(demand,digits=0)
  demand[demand<0] <- 0
  
  return(data.frame(Date=months, Quantity=demand))
}

exampleDataGen <- function(customerList, productCategories, destinationList, 
                           startDate = as.Date("2015-01-01"),
                           endDate = as.Date("2017-05-01"),
                           baselineDemand = 100,
                           seasonalAmp=10, seasonalPhase=-0.8, noiseSigma=5)
{
  # Get all the combinations of levels and group them
  combo.df <- getCombos(customerList, productCategories, destinationList) %>%
              tbl_df() %>% group_by(CustomerName, ProductCategory, Destination)
  
  # Generate time series for each combo
  historicDemand.df <- combo.df %>% do(generateDemand(startDate = startDate,
                                                endDate = endDate,
                                                baselineDemand = rnorm(1, mean=baselineDemand, sd=baselineDemand/2),
                                                seasonalAmp = rnorm(1, mean=seasonalAmp, sd=seasonalAmp),
                                                seasonalPhase = rnorm(1, mean=seasonalPhase, sd=abs(seasonalPhase)),
                                                noiseSigma = runif(1, min=noiseSigma/2, max=2*noiseSigma)))
  
  return(historicDemand.df)
}
