library(dplyr)
library(RODBC)

#####################################################################
# Make example demand data by customer, product, and destination
#
# The data is generated by finding all the possible combinations of
# the three hierarchy levels and then, for each combination,
# generating a time series which is in the form of:
# demand = const + seasonal_variation + gaussian_noise
#
# The central function is exampleDataGen. It will return a data frame
# with our defined historic demand schema. 
# 
# Fill in the SQL Server credentials and source this script to write the 
# demand data to the HistoricalOrders table
#
#####################################################################

# Default Hierarchy 
customerList <- c("Contoso","Protoso")
productCategories <- c("Plastics","Metals")
destinationList <- c("China","United States","India")

# SQL Server credentials
myServer <- "<server>.database.windows.net"
myUser <- "<user>"
myPassword <- "<passwd>"
myDatabase <- "DemandDW"
myDriver <- "SQL Server"
myTable <- "FcastML.HistoricalOrders"

# Do some outer products to generate the full data frame of product hierarchies
getCombos <- function(customerList, productCategories, destinationList) {
  
  ncust <- length(customerList)
  nprod <- length(productCategories)
  ndest <- length(destinationList)
  
  midlayer <- lapply(1:(ncust*nprod), 
                 function(i) c(customerList[floor((i-1)/nprod) + 1], productCategories[(i-1)%%nprod + 1]))
  
  lowlayer <- lapply(1:(ncust*nprod*ndest),
                 function(i) c(midlayer[[floor((i-1)/ndest) + 1]], destinationList[(i-1)%%ndest + 1]))
  
  combo.df <- bind_rows(lapply(lowlayer, 
                               function(v) as.data.frame(matrix(v, nrow = 1))))
  colnames(combo.df) <- c("CustomerName","ProductCategory","Destination")
  
  return(combo.df)
}

# Generate a single demand time series
generateDemand <- function(startDate = as.Date("2015-01-01"),
                           endDate = as.Date("2017-05-01"),
                           baselineDemand = 100,
                           seasonalAmp=10, seasonalPhase=0, noiseSigma=5) {
  
  months <- seq(from=startDate, to=endDate, by="month")
  monthsElapsed <- seq(from=0, along.with = months)
  nmonths <- length(months)
  
  # make some very fake demand data
  demand <- baselineDemand + seasonalAmp*cos(2*pi*(monthsElapsed - seasonalPhase)/12) + 
    rnorm(nmonths, sd = noiseSigma) 
  demand <- round(demand,digits=0)
  demand[demand<0] <- 0
  
  return(data.frame(Date=months, Quantity=demand))
}

# Generate full data frame of demand  - one series for each 
# leaf in the hierarchy
# Demand parameters are given by generator functions
exampleDataGen <- function(customerList, productCategories, destinationList, 
                           startDate = as.Date("2015-01-01"),
                           endDate = as.Date("2017-05-01"),
                           baselineDemandGen = function() rnorm(1, mean=100, sd=50),
                           seasonalAmpGen = function() rnorm(1, mean=15, sd=15),
                           seasonalPhaseGen = function() rnorm(1, mean=-0.8, sd=3),
                           noiseSigmaGen = function() runif(1, min=5, max=25))                                      
                           
{
  # Get all the combinations of levels and group them
  combo.df <- getCombos(customerList, productCategories, destinationList) %>%
              tbl_df() %>% group_by(CustomerName, ProductCategory, Destination)
  
  # Generate time series for each combo
  historicDemand.df <- combo.df %>% do(generateDemand(startDate = startDate,
                                                endDate = endDate,
                                                baselineDemand = baselineDemandGen(),
                                                seasonalAmp = seasonalAmpGen(),
                                                seasonalPhase = seasonalPhaseGen(),
                                                noiseSigma = noiseSigmaGen()))
  
  return(historicDemand.df)
}

# Save the data.frame dat to sqlTable in the specified SQL DB
saveToDb <- function(dat, sqlTable, dbServer, dbUsername, dbPassword, dbDatabase, dbDriver){
  
  # Build the connection string  
  connectionString <- paste0(
    "Driver=", dbDriver, 
    ";Server=", dbServer, 
    ";Database=", dbDatabase, 
    ";Uid=", dbUsername, 
    ";Pwd=", dbPassword)
  
  # Open your RODBC connection
  myconn <- odbcDriverConnect(connectionString)
  
  if(myconn==-1) {
    stop(paste("Error connecting to SQL Server. Connection string:",connectionString))
  }
  
  sqlDrop(myconn, sqlTable)
  
  varTypes <- list("nvarchar(100)", "nvarchar(100)", "nvarchar(100)", "date", "float")
  names(varTypes) <- names(dat)
  
  sqlSave(myconn, dat, tablename=sqlTable, rownames = F, varTypes = varTypes)
  
  # Close the connection
  odbcCloseAll()
  
}

# Generate default data and save to database

print("Generating demand data...")
exampleDat <- exampleDataGen(customerList, productCategories, destinationList)

print("Writing to database...")
saveToDb(data.frame(exampleDat), myTable, myServer, myUser, myPassword, myDatabase, myDriver)
